import { Appointment, AppointmentData, Doctor, Hospital, userdatas } from "../types/type";
import Logo from "../assets/logo.png";
import Hero from "../assets/hero.jpg";
import doc15 from "./doc15.png";
import doc1 from "./doc1.png";
import Sub from "./sub.png";
import doc2 from "./doc2.png";
import doc3 from "./doc3.png";
import doc4 from "./doc4.png";
import doc5 from "./doc5.png";
import doc6 from "./doc6.png";
import doc7 from "./doc7.png";
import doc8 from "./doc8.png";
import doc9 from "./doc9.png";
import doc10 from "./doc10.png";
import doc11 from "./doc11.png";
import doc12 from "./doc12.png";
import doc13 from "./doc13.png";
import doc14 from "./doc14.png";
import hospital1 from "./hospiat2.avif";
import hospital2 from "./hospiatl1.webp";
import hospital3 from "./hospiatl3.jpg";
import hospital4 from "./hospiatl4.webp";
import hospital5 from "./hospiatl5.jpg";
import hospital6 from "./hospiatl6jpg.jpg";
import hospital7 from "./hospiatl7.webp";
import hospital8 from "./hospiatl8jpg.jpg";
import hospital9 from "./hospiatl9.jpg";
import hospital10 from "./hospiatl9.jpg";
import hospital11 from "./hospiatl11.jpg";
import hospital12 from "./hospiatl12.jpg";
import hospital13 from "./hospiatl13.webp";
import hospital14 from "./hospiatl14jpg.jpg";
import hospital15 from "./hospiatl15.webp";
import hospital16 from "./hospiatl16.jpg";
import hospital17 from "./hospiatl17.webp";
import hospital18 from "./hospiatl18.webp";
import hospital19 from "./hospiatl19.jpg";
import hospital20 from "./hospiatl20.jpg";

export const assets = {
  Sub,
  Logo,
  Hero,
  doc1,
  doc2,
  doc3,
  doc4,
  doc5,
  doc6,
  doc7,
  doc8,
  doc9,
  doc10,
  doc11,
  doc12,
  doc13,
  doc14,
  doc15,
  hospital1,
  hospital2,
  hospital3,
  hospital4,
  hospital5,
  hospital6,
  hospital7,
  hospital8,
  hospital9,
  hospital10,
  hospital11,
  hospital12,
  hospital13,
  hospital14,
  hospital15,
  hospital16,
  hospital17,
  hospital18,
  hospital19,
  hospital20,
};

export const hospitals: Hospital[] = [
  {
    _id: '1',
    Hospital_Name: "Cityview Medical Center",
    Address: "101 Cityview Blvd, Los Angeles, CA 90001, USA",
    Email: "info@cityviewmed.com",
    Phone_Number: "+1 (213) 555-0234",
    Website: "www.cityviewmed.com",
    ProfilePic: hospital1,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "osun",
    picBanner: hospital10,
    Type: "General",
    ownership: "Private",
    facility: ['lab', 'clinic'],
    Available_Specialists: [
      "Cardiologists",
      "Neurologists",
      "General Surgeons",
      "Orthopedic",
      "Pediatricians",
    ],
    About:
      "Cityview Medical Center offers exceptional healthcare services in a wide range of specialties with an emphasis on patient-centered care.",
  },
  {
    _id: '2',
    Hospital_Name: "Green Valley Hospital",
    Address: "200 Green Valley Rd, Greenfield, OH 43123, USA",
    Email: "contact@greenvalleyhospital.org",
    Phone_Number: "+1 (740) 555-0456",
    Website: "www.greenvalleyhospital.org",
    ProfilePic: hospital2,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "General",
    ownership: "Public",
    facility: ['lab'],
    Available_Specialists: [
      "Internal Medicine",
      "Endocrinology",
      "Rheumatology",
      "Pulmonology",
    ],
    About:
      "Green Valley Hospital serves the Greenfield community with comprehensive general healthcare, including preventive services, emergency care, and specialist consultations.",
  },
  {
    _id: '3',
    Hospital_Name: "Oakwood Health Center",
    Address: "12 Oakwood St, Oakridge, TX 77520, USA",
    Email: "oakwoodhealth@outlook.com",
    Phone_Number: "+1 (409) 555-0978",
    Website: "www.oakwoodhealthcenter.com",
    ProfilePic: hospital3,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Clinic",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: ["Family Medicine", "Gynecology", "Dermatology"],
    About:
      "Oakwood Health Center is a private outpatient facility focused on providing high-quality primary care and specialized services in a comfortable, patient-friendly environment.",
  },
  {
    _id: '4',
    Hospital_Name: "Willowbrook University Hospital",
    Address: "300 Willowbrook Ave, New York, NY 10001, USA",
    Email: "info@willowbrookuh.edu",
    Phone_Number: "+1 (212) 555-0211",
    Website: "www.willowbrookuh.edu",
    ProfilePic: hospital4,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Teaching",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Trauma Surgeons",
      "Oncologists",
      "Pediatricians",
      "Anesthesiologists",
    ],
    About:
      "Willowbrook University Hospital integrates medical education with patient care, providing students with hands-on training while offering a range of cutting-edge medical treatments.",
  },
  {
    _id: '5',
    Hospital_Name: "Riverside Specialist Hospital",
    Address: "789 Riverside Dr, Clearwater, FL 33755, USA",
    Email: "contact@riversidespecialist.org",
    Phone_Number: "+1 (727) 555-0137",
    Website: "www.riversidespecialist.org",
    ProfilePic: hospital5,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Neurosurgeons",
      "Rheumatologists",
      "Dermatologists",
      "Cardiologists",
    ],
    About:
      "Riverside Specialist Hospital specializes in advanced treatments for complex medical conditions, providing expert care in a wide range of specialties.",
  },
  {
    _id: '6',
    Hospital_Name: "Hillside Medical Center",
    Address: "150 Hillside Rd, Montclair, NJ 07042, USA",
    Email: "contact@hillsidemedcenter.com",
    Phone_Number: "+1 (973) 555-0218",
    Website: "www.hillsidemedcenter.com",
    ProfilePic: hospital6,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "General",
    ownership: "Public",
    facility: ['lab'],
    Available_Specialists: [
      "General Practitioners",
      "Ophthalmologists",
      "Orthopedic Surgeons",
    ],
    About:
      "Hillside Medical Center offers comprehensive healthcare with an emphasis on family medicine, preventive care, and emergency services.",
  },
  {
    _id: '7',
    Hospital_Name: "Harmony Wellness Clinic",
    Address: "350 Harmony St, Dallas, TX 75202, USA",
    Email: "info@harmonywellnessclinic.com",
    Phone_Number: "+1 (214) 555-0678",
    Website: "www.harmonywellnessclinic.com",
    ProfilePic: hospital7,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "osun",
    picBanner: hospital10,
    Type: "Clinic",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Physical Therapists",
      "Nutritionists",
      "Family Physicians",
    ],
    About:
      "A dedicated clinic focused on holistic healthcare, Harmony Wellness Clinic provides services for wellness, rehabilitation, and nutrition.",
  },
  {
    _id: '8',
    Hospital_Name: "Phoenix Teaching Hospital",
    Address: "123 Phoenix Blvd, Phoenix, AZ 85001, USA",
    Email: "contact@phoenixth.edu",
    Phone_Number: "+1 (602) 555-0459",
    Website: "www.phoenixth.edu",
    ProfilePic: hospital8,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Teaching",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Cardiologists",
      "Surgeons",
      "Psychiatrists",
      "Obstetricians",
    ],
    About:
      "Phoenix Teaching Hospital provides medical education opportunities while delivering high-quality healthcare. It serves a diverse community with an extensive list of specialties.",
  },
  {
    _id: '9',
    Hospital_Name: "Blue Ridge Medical Complex",
    Address: "890 Blue Ridge Rd, Asheville, NC 28801, USA",
    Email: "support@blueridgemedical.com",
    Phone_Number: "+1 (828) 555-0345",
    Website: "www.blueridgemedical.com",
    ProfilePic: hospital9,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "General",
    ownership: "Public",
    facility: ['lab'],
    Available_Specialists: ["Dermatologists", "General Surgeons", "Urologists"],
    About:
      "Blue Ridge Medical Complex is dedicated to providing a wide range of medical services, from family care to specialized treatments.",
  },
  {
    _id: '10',
    Hospital_Name: "Summit Cancer Hospital",
    Address: "300 Summit Dr, Denver, CO 80202, USA",
    Email: "info@summitcancerhospital.com",
    Phone_Number: "+1 (303) 555-0132",
    Website: "www.summitcancerhospital.com",
    ProfilePic: hospital11,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Oncologists",
      "Radiation Therapists",
      "Palliative Care Specialists",
    ],
    About:
      "Summit Cancer Hospital is dedicated to providing the latest in cancer treatment and care, including clinical trials and advanced therapies.",
  },
  {
    _id: '11',
    Hospital_Name: "Redwood Psychiatric Hospital",
    Address: "500 Redwood Blvd, Sacramento, CA 95814, USA",
    Email: "contact@redwoodpsych.org",
    Phone_Number: "+1 (916) 555-0897",
    Website: "www.redwoodpsych.org",
    ProfilePic: hospital12,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Public",
    facility: ['lab'],
    Available_Specialists: ["Psychiatrists", "Psychologists", "Therapists"],
    About:
      "Redwood Psychiatric Hospital is focused on mental health treatment, offering inpatient and outpatient care for individuals facing a variety of psychological challenges.",
  },
  {
    _id: '12',
    Hospital_Name: "Valley Springs Hospital",
    Address: "223 Valley Springs Rd, Salt Lake City, UT 84101, USA",
    Email: "info@valleyspringshospital.com",
    Phone_Number: "+1 (385) 555-0789",
    Website: "www.valleyspringshospital.com",
    ProfilePic: hospital13,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "General",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: ["Rheumatologists", "Pulmonologists", "Surgeons"],
    About:
      "Valley Springs Hospital offers quality general healthcare, specializing in preventive care, diagnostic imaging, and emergency services.",
  },
  {
    _id: '13',
    Hospital_Name: "Crestwood Heart Institute",
    Address: "560 Crestwood Ave, San Diego, CA 92103, USA",
    Email: "info@crestwoodheart.com",
    Phone_Number: "+1 (858) 555-0201",
    Website: "www.crestwoodheart.com",
    ProfilePic: hospital14,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: ["Cardiologists", "Vascular Surgeons"],
    About:
      "Crestwood Heart Institute is renowned for its specialized care in cardiology, offering both inpatient and outpatient services, with cutting-edge diagnostic technology.",
  },
  {
    _id: '14',
    Hospital_Name: "Grace Women’s Hospital",
    Address: "120 Grace Ave, Chicago, IL 60605, USA",
    Email: "info@gracewomenshospital.com",
    Phone_Number: "+1 (312) 555-0198",
    Website: "www.gracewomenshospital.com",
    ProfilePic: hospital15,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Obstetricians",
      "Gynecologists",
      "Fertility Specialists",
    ],
    About:
      "Grace Women’s Hospital specializes in women’s health, offering a variety of services from routine check-ups to advanced gynecological surgeries and fertility treatments.",
  },
  {
    _id: '15',
    Hospital_Name: "Lakeside Orthopedic Center",
    Address: "100 Lakeside Dr, Seattle, WA 98101, USA",
    Email: "contact@lakesideorthocenter.com",
    Phone_Number: "+1 (206) 555-0213",
    Website: "www.lakesideorthocenter.com",
    ProfilePic: hospital16,
    OtherImages: [hospital17, hospital18, hospital19, hospital20],
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    AddressState: "lagos",
    picBanner: hospital10,
    Type: "Specialist",
    ownership: "Private",
    facility: ['lab'],
    Available_Specialists: [
      "Orthopedic Surgeons",
      "Sports Medicine Specialists",
    ],
    About:
      "Lakeside Orthopedic Center is a specialized hospital focused on musculoskeletal care, providing both surgical and non-surgical treatments for a variety of orthopedic conditions.",
  },
];

export const doctors: Doctor[] = [
  {
    About:
      " Cardiologists is a highly experienced cardiologists offering expert care at Cityview Medical Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.williams@cityviewmedicalcenter.medcenter.org",
    Experience: "20 years",
    AddressState: "oyo",
    Field: "Cardiologists",
    Hospital_Name: "Cityview Medical Center",
    Name: "Emma Williams",
    Phone: "+1 (213) 552-0234",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaWilliams.net",
    _id: '1'
  },
  {
    About:
      " General is a highly experienced general surgeon offering expert care at Cityview Medical Center.",
    ProfilePic: doc2,
    picBanner: doc2,
    avalaibility: 'offline',
    College: "Harvard Medical School",
    Email: "daniel.jones@cityviewmedicalcenter.medcenter.org",
    Experience: "25 years",
    AddressState: "lagos",
    Field: "General Surgeons",
    Hospital_Name: "Cityview Medical Center",
    Name: "  Daniel Jones",
    Phone: "+1 (213) 554-0234",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielJones.net",
    _id: '3'
  },
  {
    About:
      " Orthopedic is a highly experienced orthopedic surgeons offering expert care at Cityview Medical Center.",
    ProfilePic: doc3,
    picBanner: doc3,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "david.smith@cityviewmedicalcenter.healthcare.net",
    Experience: "11 years",
    AddressState: "lagos",
    Field: "Orthopedic",
    Hospital_Name: "Cityview Medical Center",
    Name: "  David Smith",
    Phone: "+1 (213) 555-0234",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },

      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidSmith.net",
    _id: '4'
  },
  {
    About:
      " Pediatricians is a highly experienced pediatricians offering expert care at Cityview Medical Center.",
    ProfilePic: doc4,
    picBanner: doc4,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.smith@cityviewmedicalcenter.medcenter.org",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Pediatricians",
    Hospital_Name: "Cityview Medical Center",
    Name: "  Liam Smith",
    Phone: "+1 (213) 556-0234",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamSmith.net",
    _id: '5',
  },
  {
    About:
      " Internal is a highly experienced internal medicine offering expert care at Green Valley Hospital.",
    ProfilePic: doc5,
    picBanner: doc5,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.jones@greenvalleyhospital.medcenter.org",
    Experience: "25 years",
    AddressState: "lagos",
    Field: "Internal Medicine",
    Hospital_Name: "Green Valley Hospital",
    Name: "  Emma Jones",
    Phone: "+1 (740) 557-0456",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaJones.net",
    _id: '6',
  },
  {
    About:
      " Endocrinology is a highly experienced endocrinology offering expert care at Green Valley Hospital.",
    ProfilePic: doc6,
    picBanner: doc6,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.smith@greenvalleyhospital.medcenter.org",
    Experience: "12 years",
    AddressState: "lagos",
    Field: "Endocrinology",
    Hospital_Name: "Green Valley Hospital",
    Name: "  Michael Smith",
    Phone: "+1 (740) 558-0456",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelSmith.net",
    _id: '7',
  },
  {
    About:
      " Rheumatology is a highly experienced rheumatology offering expert care at Green Valley Hospital.",
    ProfilePic: doc7,
    picBanner: doc7,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.jones@greenvalleyhospital.medcenter.org",
    Experience: "8 years",
    AddressState: "lagos",
    Field: "Rheumatology",
    Hospital_Name: "Green Valley Hospital",
    Name: "  Liam Jones",
    Phone: "+1 (740) 559-0456",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamJones.net",
    _id: '8',
  },
  {
    About:
      " Pulmonology is a highly experienced pulmonology offering expert care at Green Valley Hospital.",
    ProfilePic: doc8,
    picBanner: doc8,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.smith@greenvalleyhospital.hospital.com",
    Experience: "10 years",
    AddressState: "lagos",
    Field: "Pulmonology",
    Hospital_Name: "Green Valley Hospital",
    Name: "  Michael Smith",
    Phone: "+1 (740) 5510-0456",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],

    Website: "MichaelSmith.net",
    _id: '9',
  },
  {
    About:
      " Family is a highly experienced family medicine offering expert care at Oakwood Health Center.",
    ProfilePic: doc9,
    picBanner: doc9,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.smith@oakwoodhealthcenter.healthcare.net",
    Experience: "12 years",
    AddressState: "lagos",
    Field: "Family Medicine",
    Hospital_Name: "Oakwood Health Center",
    Name: "  Daniel Smith",
    Phone: "+1 (409) 5511-0978",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielSmith.net",
    _id: '10',
  },
  {
    About:
      " Gynecology is a highly experienced gynecology offering expert care at Oakwood Health Center.",
    ProfilePic: doc10,
    picBanner: doc10,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sarah.martinez@oakwoodhealthcenter.medcenter.org",
    Experience: "7 years",
    AddressState: "lagos",
    Field: "Gynecology",
    Hospital_Name: "Oakwood Health Center",
    Name: "  Sarah Martinez",
    Phone: "+1 (409) 5512-0978",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SarahMartinez.net",
    _id: '11',
  },
  {
    About:
      " Dermatology is a highly experienced dermatology offering expert care at Oakwood Health Center.",
    ProfilePic: doc11,
    picBanner: doc11,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.brown@oakwoodhealthcenter.healthcare.net",
    Experience: "13 years",
    AddressState: "lagos",
    Field: "Dermatology",
    Hospital_Name: "Oakwood Health Center",
    Name: "  Daniel Brown",
    Phone: "+1 (409) 5513-0978",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielBrown.net",
    _id: '12',
  },
  {
    About:
      " Trauma is a highly experienced trauma surgeons offering expert care at Willowbrook University Hospital.",
    ProfilePic: doc12,
    picBanner: doc12,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.jones@willowbrookuniversityhospital.medcenter.org",
    Experience: "14 years",
    AddressState: "lagos",
    Field: "Trauma Surgeons",
    Hospital_Name: "Willowbrook University Hospital",
    Name: "  Liam Jones",
    Phone: "+1 (212) 5514-0211",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamJones.net",
    _id: '13',
  },
  {
    About:
      " Oncologists is a highly experienced oncologists offering expert care at Willowbrook University Hospital.",
    ProfilePic: doc13,
    picBanner: doc13,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.jones@willowbrookuniversityhospital.hospital.com",
    Experience: "5 years",
    AddressState: "lagos",
    Field: "Oncologists",
    Hospital_Name: "Willowbrook University Hospital",
    Name: "  Daniel Jones",
    Phone: "+1 (212) 5515-0211",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielJones.net",
    _id: '14',
  },
  {
    About:
      " Pediatricians is a highly experienced pediatricians offering expert care at Willowbrook University Hospital.",
    ProfilePic: doc14,
    picBanner: doc14,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.williams@willowbrookuniversityhospital.medcenter.org",
    Experience: "16 years",
    AddressState: "lagos",
    Field: "Pediatricians",
    Hospital_Name: "Willowbrook University Hospital",
    Name: "  Michael Williams",
    Phone: "+1 (212) 5516-0211",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelWilliams.net",
    _id: '15',
  },
  {
    About:
      " Anesthesiologists is a highly experienced anesthesiologists offering expert care at Willowbrook University Hospital.",
    ProfilePic: doc15,
    picBanner: doc15,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.smith@willowbrookuniversityhospital.healthcare.net",
    Experience: "8 years",
    AddressState: "lagos",
    Field: "Anesthesiologists",
    Hospital_Name: "Willowbrook University Hospital",
    Name: "  Daniel Smith",
    Phone: "+1 (212) 5517-0211",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielSmith.net",
    _id: '16',
  },
  {
    About:
      " Neurosurgeons is a highly experienced neurosurgeons offering expert care at Riverside Specialist Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sarah.brown@riversidespecialisthospital.hospital.com",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Neurosurgeons",
    Hospital_Name: "Riverside Specialist Hospital",
    Name: "  Sarah Brown",
    Phone: "+1 (727) 5518-0137",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SarahBrown.net",
    _id: '17',
  },
  {
    About:
      " Rheumatologists is a highly experienced rheumatologists offering expert care at Riverside Specialist Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.jones@riversidespecialisthospital.healthcare.net",
    Experience: "22 years",
    AddressState: "lagos",
    Field: "Rheumatologists",
    Hospital_Name: "Riverside Specialist Hospital",
    Name: "  Liam Jones",
    Phone: "+1 (727) 5519-0137",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],

    Website: "LiamJones.net",
    _id: '18',
  },
  {
    About:
      " Dermatologists is a highly experienced dermatologists offering expert care at Riverside Specialist Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.taylor@riversidespecialisthospital.hospital.com",
    Experience: "12 years",
    AddressState: "lagos",
    Field: "Dermatologists",
    Hospital_Name: "Riverside Specialist Hospital",
    Name: "  Liam Taylor",
    Phone: "+1 (727) 5520-0137",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamTaylor.net",
    _id: '19',
  },
  {
    About:
      " Cardiologists is a highly experienced cardiologists offering expert care at Riverside Specialist Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "david.smith@riversidespecialisthospital.medcenter.org",
    Experience: "20 years",
    AddressState: "lagos",
    Field: "Cardiologists",
    Hospital_Name: "Riverside Specialist Hospital",
    Name: "  David Smith",
    Phone: "+1 (727) 5521-0137",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidSmith.net",
    _id: '20',
  },

  {
    About:
      " General is a highly experienced general practitioners offering expert care at Hillside Medical Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.williams@hillsidemedicalcenter.hospital.com",
    Experience: "24 years",
    AddressState: "lagos",
    Field: "General Practitioners",
    Hospital_Name: "Hillside Medical Center",
    Name: "  Liam Williams",
    Phone: "+1 (973) 5522-0218",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamWilliams.net",
    _id: '21',
  },
  {
    About:
      " Ophthalmologists is a highly experienced ophthalmologists offering expert care at Hillside Medical Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.taylor@hillsidemedicalcenter.hospital.com",
    Experience: "12 years",
    AddressState: "lagos",
    Field: "Ophthalmologists",
    Hospital_Name: "Hillside Medical Center",
    Name: "  Emma Taylor",
    Phone: "+1 (973) 5523-0218",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaTaylor.net",
    _id: '22',
  },
  {
    About:
      " Orthopedic is a highly experienced orthopedic surgeons offering expert care at Hillside Medical Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'offline',
    College: "Harvard Medical School",
    Email: "david.martinez@hillsidemedicalcenter.hospital.com",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Orthopedic",
    Hospital_Name: "Hillside Medical Center",
    Name: "  David Martinez",
    Phone: "+1 (973) 5524-0218",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidMartinez.net",
    _id: '23',
  },

  {
    About:
      " Physical is a highly experienced physical therapists offering expert care at Harmony Wellness Clinic.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "david.taylor@harmonywellnessclinic.hospital.com",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Physical Therapists",
    Hospital_Name: "Harmony Wellness Clinic",
    Name: "  David Taylor",
    Phone: "+1 (214) 5525-0678",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidTaylor.net",
    _id: '24',
  },
  {
    About:
      " Nutritionists is a highly experienced nutritionists offering expert care at Harmony Wellness Clinic.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.garcia@harmonywellnessclinic.hospital.com",
    Experience: "14 years",
    AddressState: "lagos",
    Field: "Nutritionists",
    Hospital_Name: "Harmony Wellness Clinic",
    Name: "  Liam Garcia",
    Phone: "+1 (214) 5526-0678",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamGarcia.net",
    _id: '25',
  },
  {
    About:
      " Family is a highly experienced family physicians offering expert care at Harmony Wellness Clinic.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.taylor@harmonywellnessclinic.medcenter.org",
    Experience: "21 years",
    AddressState: "lagos",
    Field: "Family Physicians",
    Hospital_Name: "Harmony Wellness Clinic",
    Name: "  Daniel Taylor",
    Phone: "+1 (214) 5527-0678",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielTaylor.net",
    _id: '26',
  },

  {
    About:
      " Cardiologists is a highly experienced cardiologists offering expert care at Phoenix Teaching Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.williams@phoenixteachinghospital.medcenter.org",
    Experience: "20 years",
    AddressState: "lagos",
    Field: "Cardiologists",
    Hospital_Name: "Phoenix Teaching Hospital",
    Name: "  Emma Williams",
    Phone: "+1 (602) 5528-0459",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaWilliams.net",
    _id: '27',
  },
  {
    About:
      " Surgeons is a highly experienced surgeons offering expert care at Phoenix Teaching Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sophia.garcia@phoenixteachinghospital.hospital.com",
    Experience: "7 years",
    AddressState: "lagos",
    Field: "Surgeons",
    Hospital_Name: "Phoenix Teaching Hospital",
    Name: "  Sophia Garcia",
    Phone: "+1 (602) 5529-0459",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SophiaGarcia.net",
    _id: '28',
  },

  {
    About:
      " Psychiatrists is a highly experienced psychiatrists offering expert care at Phoenix Teaching Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.jones@phoenixteachinghospital.medcenter.org",
    Experience: "5 years",
    AddressState: "lagos",
    Field: "Psychiatrists",
    Hospital_Name: "Phoenix Teaching Hospital",
    Name: "  Liam Jones",
    Phone: "+1 (602) 5530-0459",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamJones.net",
    _id: '29',
  },
  {
    About:
      " Obstetricians is a highly experienced obstetricians offering expert care at Phoenix Teaching Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.martinez@phoenixteachinghospital.healthcare.net",
    Experience: "19 years",
    AddressState: "lagos",
    Field: "Obstetricians",
    Hospital_Name: "Phoenix Teaching Hospital",
    Name: "  Liam Martinez",
    Phone: "+1 (602) 5531-0459",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamMartinez.net",
    _id: '30',
  },

  {
    About:
      " Dermatologists is a highly experienced dermatologists offering expert care at Blue Ridge Medical Complex.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.williams@blueridgemedicalcomplex.medcenter.org",
    Experience: "10 years",
    AddressState: "lagos",
    Field: "Dermatologists",
    Hospital_Name: "Blue Ridge Medical Complex",
    Name: "  Emma Williams",
    Phone: "+1 (828) 5532-0345",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaWilliams.net",
    _id: '31',
  },
  {
    About:
      " General is a highly experienced general surgeons offering expert care at Blue Ridge Medical Complex.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.brown@blueridgemedicalcomplex.hospital.com",
    Experience: "14 years",
    AddressState: "lagos",
    Field: "General Surgeons",
    Hospital_Name: "Blue Ridge Medical Complex",
    Name: "  Michael Brown",
    Phone: "+1 (828) 5533-0345",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelBrown.net",
    _id: '32',
  },
  {
    About:
      " Urologists is a highly experienced urologists offering expert care at Blue Ridge Medical Complex.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.martinez@blueridgemedicalcomplex.hospital.com",
    Experience: "13 years",
    AddressState: "lagos",
    Field: "Urologists",
    Hospital_Name: "Blue Ridge Medical Complex",
    Name: "  Michael Martinez",
    Phone: "+1 (828) 5534-0345",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelMartinez.net",
    _id: '33',
  },
  {
    About:
      " Oncologists is a highly experienced oncologists offering expert care at Summit Cancer Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sarah.smith@summitcancerhospital.medcenter.org",
    Experience: "24 years",
    AddressState: "lagos",
    Field: "Oncologists",
    Hospital_Name: "Summit Cancer Hospital",
    Name: "  Sarah Smith",
    Phone: "+1 (303) 5535-0132",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SarahSmith.net",
    _id: '34',
  },
  {
    About:
      " Radiation is a highly experienced radiation therapists offering expert care at Summit Cancer Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sarah.williams@summitcancerhospital.hospital.com",
    Experience: "12 years",
    AddressState: "lagos",
    Field: "Radiation Therapists",
    Hospital_Name: "Summit Cancer Hospital",
    Name: "  Sarah Williams",
    Phone: "+1 (303) 5536-0132",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SarahWilliams.net",
    _id: '35',
  },
  {
    About:
      " Palliative is a highly experienced palliative care specialists offering expert care at Summit Cancer Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.garcia@summitcancerhospital.healthcare.net",
    Experience: "23 years",
    AddressState: "lagos",
    Field: "Palliative Care Specialists",
    Hospital_Name: "Summit Cancer Hospital",
    Name: "  Daniel Garcia",
    Phone: "+1 (303) 5537-0132",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielGarcia.net",
    _id: '36',
  },
  {
    About:
      " Psychiatrists is a highly experienced psychiatrists offering expert care at Redwood Psychiatric Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.martinez@redwoodpsychiatrichospital.healthcare.net",
    Experience: "10 years",
    AddressState: "lagos",
    Field: "Psychiatrists",
    Hospital_Name: "Redwood Psychiatric Hospital",
    Name: "  Liam Martinez",
    Phone: "+1 (916) 5538-0897",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamMartinez.net",
    _id: '37',
  },
  {
    About:
      " Psychologists is a highly experienced psychologists offering expert care at Redwood Psychiatric Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.taylor@redwoodpsychiatrichospital.hospital.com",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Psychologists",
    Hospital_Name: "Redwood Psychiatric Hospital",
    Name: "  Daniel Taylor",
    Phone: "+1 (916) 5539-0897",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielTaylor.net",
    _id: '38',
  },
  {
    About:
      " Therapists is a highly experienced therapists offering expert care at Redwood Psychiatric Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sarah.williams@redwoodpsychiatrichospital.healthcare.net",
    Experience: "22 years",
    AddressState: "lagos",
    Field: "Therapists",
    Hospital_Name: "Redwood Psychiatric Hospital",
    Name: "  Sarah Williams",
    Phone: "+1 (916) 5540-0897",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SarahWilliams.net",
    _id: '39',
  },
  {
    About:
      " Rheumatologists is a highly experienced rheumatologists offering expert care at Valley Springs Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "emma.smith@valleyspringshospital.healthcare.net",
    Experience: "22 years",
    AddressState: "lagos",
    Field: "Rheumatologists",
    Hospital_Name: "Valley Springs Hospital",
    Name: "  Emma Smith",
    Phone: "+1 (385) 5541-0789",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "EmmaSmith.net",
    _id: '40',
  },
  {
    About:
      " Pulmonologists is a highly experienced pulmonologists offering expert care at Valley Springs Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.martinez@valleyspringshospital.healthcare.net",
    Experience: "22 years",
    AddressState: "lagos",
    Field: "Pulmonologists",
    Hospital_Name: "Valley Springs Hospital",
    Name: "  Michael Martinez",
    Phone: "+1 (385) 5542-0789",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelMartinez.net",
    _id: '41',
  },
  {
    About:
      " Surgeons is a highly experienced surgeons offering expert care at Valley Springs Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "david.williams@valleyspringshospital.healthcare.net",
    Experience: "17 years",
    AddressState: "lagos",
    Field: "Surgeons",
    Hospital_Name: "Valley Springs Hospital",
    Name: "  David Williams",
    Phone: "+1 (385) 5543-0789",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidWilliams.net",
    _id: '42',
  },

  {
    About:
      " Cardiologists is a highly experienced cardiologists offering expert care at Crestwood Heart Institute.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "david.martinez@crestwoodheartinstitute.medcenter.org",
    Experience: "14 years",
    AddressState: "lagos",
    Field: "Cardiologists",
    Hospital_Name: "Crestwood Heart Institute",
    Name: "  David Martinez",
    Phone: "+1 (858) 5544-0201",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DavidMartinez.net",
    _id: '43',
  },

  {
    About:
      " Vascular is a highly experienced vascular surgeons offering expert care at Crestwood Heart Institute.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.jones@crestwoodheartinstitute.hospital.com",
    Experience: "18 years",
    AddressState: "lagos",
    Field: "Vascular Surgeons",
    Hospital_Name: "Crestwood Heart Institute",
    Name: "  Liam Jones",
    Phone: "+1 (858) 5545-0201",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamJones.net",
    _id: '44',
  },

  {
    About:
      " Obstetricians is a highly experienced obstetricians offering expert care at Grace Women’s Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "daniel.williams@gracewomen’shospital.healthcare.net",
    Experience: "22 years",
    AddressState: "lagos",
    Field: "Obstetricians",
    Hospital_Name: "Grace Women’s Hospital",
    Name: "  Daniel Williams",
    Phone: "+1 (312) 5546-0198",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "DanielWilliams.net",
    _id: '45',
  },

  {
    About:
      " Gynecologists is a highly experienced gynecologists offering expert care at Grace Women’s Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "michael.taylor@gracewomen’shospital.medcenter.org",
    Experience: "16 years",
    AddressState: "lagos",
    Field: "Gynecologists",
    Hospital_Name: "Grace Women’s Hospital",
    Name: "  Michael Taylor",
    Phone: "+1 (312) 5547-0198",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "MichaelTaylor.net",
    _id: '46',
  },

  {
    About:
      " Fertility is a highly experienced fertility specialists offering expert care at Grace Women’s Hospital.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "liam.garcia@gracewomen’shospital.medcenter.org",
    Experience: "8 years",
    AddressState: "lagos",
    Field: "Fertility Specialists",
    Hospital_Name: "Grace Women’s Hospital",
    Name: "  Liam Garcia",
    Phone: "+1 (312) 5548-0198",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "LiamGarcia.net",
    _id: '47',
  },

  {
    About:
      " Orthopedic is a highly experienced orthopedic surgeons offering expert care at Lakeside Orthopedic Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sophia.martinez@lakesideorthopediccenter.healthcare.net",
    Experience: "5 years",
    AddressState: "lagos",
    Field: "Orthopedic",
    Hospital_Name: "Lakeside Orthopedic Center",
    Name: "  Sophia Martinez",
    Phone: "+1 (206) 5549-0213",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SophiaMartinez.net",
    _id: '48',
  },
  {
    About:
      " Sports is a highly experienced sports medicine specialists offering expert care at Lakeside Orthopedic Center.",
    ProfilePic: doc1,
    picBanner: doc1,
    avalaibility: 'online',
    College: "Harvard Medical School",
    Email: "sophia.martinez@lakesideorthopediccenter.medcenter.org",
    Experience: "14 years",
    AddressState: "lagos",
    Field: "Sports Medicine Specialists",
    Hospital_Name: "Lakeside Orthopedic Center",
    Name: "  Sophia Martinez",
    Phone: "+1 (206) 5550-0213",
    Review: [
      { Rating: 5, name: 'john doe', email: 'johndoe@email.com', Comment: "Outstanding doctor! Very thorough and caring." },
      { Rating: 4, name: 'john doe', email: 'johndoe@email.com', Comment: "Highly professional and knowledgeable." },
    ],
    Website: "SophiaMartinez.net",
    _id: '49',
  },
];
export const preference = ["Doctors", "hospitals"];

export const hopitalType = ["General", "Specialist", "Clinic"];
export const ownership = ["Private", "Public"];
export const Specialists = [
  "Cardiologists",
  "Neurologists",
  "General Surgeons",
  "Orthopedic",
  "Pediatricians",
  "Psychiatrists",
  "Internal Medicine",
  "Psychologists",
  "Therapists",
  "Endocrinology",
  "Rheumatology",
  "Pulmonology",
  "Family Medicine",
  "Gynecology",
];

export const appointments: Appointment[] = [
  {
    _id: '1',
    status: 'pending',
    date: '2025-02-11 ',
    doctor: 'Dr. John Doe',
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc1,
    time: '10:00AM'
  },
  {
    _id: '6',
    status: 'canceled',
    date: '2025-02-01',
    doctor: 'Dr. jane Doe',
    hospistal_name: 'Green Valley Hospital',
    doctor_image: doc3,
    time: '13:00'
  },
  {
    _id: '7',
    status: 'pending',
    date: '2025-02-11 ',
    doctor: 'Dr. John Doe',
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc1,
    time: '10:00AM'
  },
  {
    _id: '8',
    status: 'canceled',
    date: '2025-02-01',
    doctor: 'Dr. jane Doe',
    hospistal_name: 'Green Valley Hospital',
    doctor_image: doc3,
    time: '13:00'
  },
  {
    _id: '9',
    status: 'pending',
    date: '2025-02-11 ',
    doctor: 'Dr. John Doe',
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc1,
    time: '10:00AM'
  },
  {
    _id: '10',
    status: 'pending',
    date: '2025-02-11 ',
    doctor: 'Dr. John Doe',
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc1,
    time: '10:00AM'
  },
  {
    _id: '2',
    status: 'canceled',
    date: '2025-02-01',
    doctor: 'Dr. jane Doe',
    hospistal_name: 'Green Valley Hospital',
    doctor_image: doc3,
    time: '13:00'
  },
  {
    _id: '3',
    status: 'successful',
    date: '2025-02-01 ',
    doctor: 'Dr. John Doe',
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc4,
    time: '12:00pm'
  },

  {
    _id: "4",
    status: "successful",
    doctor: "Dr. Sarah Lee",
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc4,
    time: '11:00am',
    date: '2025-01-01 ',
  },
  {
    _id: "5",
    status: "successful",
    doctor: "Dr. Mark Smith",
    hospistal_name: 'Riverside Specialist Hospital',
    doctor_image: doc4,
    time: '2:00pm',
    date: '2025-01-28 ',

  },
]

export const appointmentsDatas: AppointmentData[] = [
  {
    _id: "1",
    status: "successful",
    doctor: "Dr. John Doe",
    reasonForVisit: "General checkup and consultation.",
    medicalHistory:
      "Patient has a history of mild hypertension and seasonal allergies.",
    vitalSigns: {
      bodyTemperature: "98.6°F",
      pulseRate: "72 bpm",
      respirationRate: "16 breaths/min",
      bloodPressure: "120/80 mmHg",
    },
    doctorDiagnosis:
      "Mild hypertension observed. Recommended lifestyle modifications.",
    doctorPrescription:
      "Prescribed low-dose aspirin and advised regular exercise.",
      appointments_id: '3'
  },
  {
    _id: "2",
    status: "canceled",
    doctor: "Dr. John Doe",
   appointments_id: '2',
   reasonforcancelation: 'doctor  ouyt of town'
  },
  
  {
    _id: "4",
    status: "successful",
    doctor: "Dr. Sarah Lee",
    reasonForVisit: "Follow-up for diabetes management.",
    medicalHistory:
      "Type 2 diabetes for 5 years. Regular insulin therapy ongoing.",
    vitalSigns: {
      bodyTemperature: "98.4°F",
      pulseRate: "80 bpm",
      respirationRate: "18 breaths/min",
      bloodPressure: "130/85 mmHg",
    },
    appointments_id: '4',
    doctorDiagnosis:
      "Blood sugar levels are stable. No complications detected.",
    doctorPrescription:
      "Continue current insulin dosage. Follow up in 3 months.",
  },
  {
    _id: "3",
    status: "successful",
    doctor: "Dr. Mark Smith",
    reasonForVisit: "Complaints of persistent migraines.",
    medicalHistory: "Frequent headaches, no known allergies.",
    vitalSigns: {
      bodyTemperature: "98.2°F",
      pulseRate: "76 bpm",
      respirationRate: "17 breaths/min",
      bloodPressure: "118/78 mmHg",
    },
    doctorDiagnosis: "Pending further tests and evaluation.",
    doctorPrescription: "Advised to maintain a headache diary.",
    appointments_id: '5'
  },
];

export const userDatas: userdatas = {
  first_name: "John",
  email: "john@doe.com",
  image: assets.doc1 as string,
  address: "hogn doe strrt",
  gender: "male",
  date: "1997-04-19",
  last_name: "doe",
  blood_group: " A+",
  blood_genotype: "ac",
  phone: "23456789097654",
  Marital_status: "single",
  state: "osun",
  kin_firstName: "jane",
  kin_lastName: "jane",
  kin_email: "john@doe.com",
  kin_address: "hogn doe strrt",
  Kin_gender: "male",
  kin_phone: "23456789097654",
  Kin_relation: "wife",
  Kin_state: "osun",
  height: '100m',
  weight: '56kg',
}

